name: app_cartao_perfil
description: Desafio do Arquiteto — cartão de perfil em Flutter (Aula 5).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
